# Generated by Django 4.2.23 on 2025-08-20 22:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=100, unique=True)),
                ('hashrate', models.FloatField(help_text='MH/s')),
                ('temperature', models.FloatField(help_text='Celsius')),
                ('status', models.CharField(choices=[('running', 'Running'), ('stopped', 'Stopped'), ('maintenance', 'Maintenance')], default='running', max_length=20)),
                ('earnings', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('uptime', models.DurationField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
