# Generated by Django 4.2.23 on 2025-08-20 22:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('desc', models.TextField()),
                ('hashrate', models.FloatField(help_text='MH/s')),
                ('daily_profit_from', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('daily_profit_to', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('wattage', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MyDeviceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hashrate', models.FloatField(help_text='MH/s')),
                ('temperature', models.FloatField(help_text='Celsius')),
                ('status', models.CharField(choices=[('running', 'Running'), ('stopped', 'Stopped'), ('maintenance', 'Maintenance')], default='running', max_length=20)),
                ('earnings', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('uptime', models.DurationField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='devices.devicemodel')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Device',
        ),
    ]
