# Generated by Django 4.2.23 on 2025-08-20 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_devicemodel_mydevicemodel_delete_device'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicemodel',
            name='image',
            field=models.ImageField(null=True, upload_to='devices/'),
        ),
    ]
