# Generated by Django 4.2.23 on 2025-08-20 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_devicemodel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicemodel',
            name='age',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
