# Generated by Django 4.2.23 on 2025-08-21 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0004_devicemodel_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicemodel',
            name='hashrate_from',
            field=models.FloatField(default=95, help_text='MH/s'),
        ),
        migrations.AddField(
            model_name='devicemodel',
            name='hashrate_to',
            field=models.FloatField(default=105, help_text='MH/s'),
        ),
        migrations.AddField(
            model_name='devicemodel',
            name='temperature_from',
            field=models.FloatField(default=65, help_text='Celsius'),
        ),
        migrations.AddField(
            model_name='devicemodel',
            name='temperature_to',
            field=models.FloatField(default=80, help_text='Celsius'),
        ),
    ]
