# Generated by Django 4.2.23 on 2025-08-21 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0005_devicemodel_hashrate_from_devicemodel_hashrate_to_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mydevicemodel',
            name='earnings',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=12),
        ),
    ]
