# Generated by Django 4.2.23 on 2025-08-24 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0006_alter_mydevicemodel_earnings'),
    ]

    operations = [
        migrations.AddField(
            model_name='mydevicemodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
