# Generated by Django 4.2.23 on 2025-08-30 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0007_mydevicemodel_updated_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='devicemodel',
            old_name='daily_profit_from',
            new_name='daily_profit',
        ),
        migrations.RenameField(
            model_name='devicemodel',
            old_name='temperature_from',
            new_name='temperature',
        ),
        migrations.RemoveField(
            model_name='devicemodel',
            name='daily_profit_to',
        ),
        migrations.RemoveField(
            model_name='devicemodel',
            name='hashrate_from',
        ),
        migrations.RemoveField(
            model_name='devicemodel',
            name='hashrate_to',
        ),
        migrations.RemoveField(
            model_name='devicemodel',
            name='temperature_to',
        ),
    ]
