# Generated by Django 4.2.23 on 2025-08-30 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0008_rename_daily_profit_from_devicemodel_daily_profit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mydevicemodel',
            name='stage',
            field=models.IntegerField(default=1),
        ),
    ]
