# Generated by Django 4.2.23 on 2025-08-30 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0009_mydevicemodel_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='mydevicemodel',
            name='wattage',
            field=models.FloatField(default=0, help_text='Wats/h'),
            preserve_default=False,
        ),
    ]
