# Generated by Django 4.2.23 on 2025-08-30 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0010_mydevicemodel_wattage'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicemodel',
            name='stage',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='mydevicemodel',
            name='consumption',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='mydevicemodel',
            name='energy_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='mydevicemodel',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='mydevicemodel',
            name='status',
            field=models.CharField(choices=[('running', 'Running'), ('stopped', 'Stopped'), ('done', 'Done'), ('maintenance', 'Maintenance')], default='running', max_length=20),
        ),
    ]
