# Generated by Django 4.2.23 on 2025-08-30 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0011_devicemodel_stage_mydevicemodel_consumption_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mydevicemodel',
            name='energy_balance',
        ),
        migrations.CreateModel(
            name='DeviceStagesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.IntegerField(default=1)),
                ('energy_balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('profit_percentage_energy_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.devicemodel')),
            ],
        ),
    ]
