# Generated by Django 4.2.23 on 2025-08-30 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0012_remove_mydevicemodel_energy_balance_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='devicestagesmodel',
            old_name='profit_percentage_energy_balance',
            new_name='profit_per_energy',
        ),
        migrations.RemoveField(
            model_name='mydevicemodel',
            name='uptime',
        ),
        migrations.AlterField(
            model_name='mydevicemodel',
            name='wattage',
            field=models.FloatField(help_text='Watts/h'),
        ),
    ]
