# Generated by Django 4.2.23 on 2025-08-30 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0013_rename_profit_percentage_energy_balance_devicestagesmodel_profit_per_energy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mydevicemodel',
            name='energy_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
