# Generated by Django 4.2.23 on 2025-08-30 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0014_mydevicemodel_energy_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devicemodel',
            name='stage',
        ),
        migrations.AddField(
            model_name='devicemodel',
            name='consumption_unit',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='devicestagesmodel',
            name='energy_balance',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
        ),
        migrations.AlterField(
            model_name='devicestagesmodel',
            name='profit_per_energy',
            field=models.DecimalField(decimal_places=2, default=0.1, max_digits=12),
        ),
        migrations.AlterField(
            model_name='devicestagesmodel',
            name='stage',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='mydevicemodel',
            name='hashrate',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='mydevicemodel',
            name='temperature',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='mydevicemodel',
            name='wattage',
            field=models.FloatField(default=0),
        ),
    ]
