# Generated by Django 4.2.23 on 2025-08-30 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0015_remove_devicemodel_stage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicemodel',
            name='consumption_unit',
            field=models.DecimalField(decimal_places=2, default=0.05, max_digits=12),
        ),
    ]
