# Generated by Django 4.2.23 on 2025-08-30 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0016_alter_devicemodel_consumption_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicemodel',
            name='stage',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='mydevicemodel',
            name='status',
            field=models.CharField(choices=[('running', 'Running'), ('stopped', 'Stopped'), ('next', 'Next'), ('done', 'Done'), ('maintenance', 'Maintenance')], default='running', max_length=20),
        ),
    ]
