# Generated by Django 4.2.23 on 2025-10-18 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0017_devicemodel_stage_alter_mydevicemodel_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='mydevicemodel',
            name='stop_continue',
            field=models.BooleanField(default=False),
        ),
    ]
