# Generated by Django 4.2.23 on 2025-11-28 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0018_mydevicemodel_stop_continue'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicemodel',
            name='view_for_not_verified',
            field=models.BooleanField(default=False, help_text='عرض هذا الجهاز لغير الموثوقين'),
        ),
    ]
