"""
Django settings for mining_platform project.

Generated by 'django-admin startproject' using Django 4.2.23.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-y%jdr#j(&g-i(vfgt=0$2ey1ff4$ycf-1m7!-(n*f$j4x-p31('

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['softmsg.com', 'www.softmsg.com', '127.0.0.1']


# Application definition

INSTALLED_APPS = [
    'management',
    'pages',
    'accounts',
    'devices',
    'investors',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_celery_beat',
    'django_celery_results',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'mining_platform.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.i18n',
            ],
        },
    },
]

WSGI_APPLICATION = 'mining_platform.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

LANGUAGE_CODE = 'en'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

USE_L10N = True


LANGUAGES = [
    ('en', 'English'),
    ('ar', 'Arabic'),
    ('ro', 'Romanian'),
    ('de', 'German'),
]

LOCALE_PATHS = [
    BASE_DIR / 'locale/',
]
# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'static'
STATICFILES_DIRS = [BASE_DIR / 'mining_platform/static']

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

PATIENT_MANAGEMENT_WEB_SERVER_URL = 'http://127.0.0.1:8001'
SCHOOL_MANAGEMENT_WEB_SERVER_URL = 'http://127.0.0.1:8002'

PAYPAL_TEST = False
PAYPAL_RECIVVER_EMAIL = 'mohammadsherms3@gmail.com'
PAYPAL_BUY_BUTTON_IMAGE = 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAMgAAABJCAYAAAB4tGnjAAAAAXNSR0IArs4c6QAADbtJREFUeF7tnXlcVOUax39nFhhghmGRRdBkF1xQcRf1KqmZW7lczU+rS2aF5oaGad6w1FIzjcpcymu3zetyu5WWKWpqgiC4s4mOLLEJAjMDDMOZcz/nzGUQZWBmgIZh3vevs7zv+zzv931/593mnKFAAiFACOglQBE2hAAhoJ8AEQhpHYRAEwSIQEjzIASIQEgbIARMI0B6ENO4kVRWQoAIxEoqmhTTNAJEIKZxI6mshAARiJVUNCmmaQSIQEzjRlJZCQEiECupaFJM0wgQgZjGjaSyEgJEIFZS0aSYphEgAjGNG0llJQSIQKykokkxTSNABGIaN5LKSggQgVhJRZNimkaACMQ0biSVlRAgArGSiibFNI1AqwrE21viOnWIeNSIvtLRXdyEQRQgNs0tkooQMJwAAyhy79Vknk2piDsSrzidlycvMTx10zFbLJAAT7HbnjU+sSP6OE6nKPBbyzGSDyFgKgGGAX32SsWh+e/KIm8VKIpNzYdNZ7JAfHzgFLclLM7HU9SvJQ6QtIRAWxKQFVSnRKxIjpDJUGaKHZME8ukKv+iFT3tuMMUgSUMImIPAzv8UrH5ty+2Nxto2WiCZB8Iu+HuJhhhriMQnBMxNICuvOj5wVvJQY/wwSiD3jw26JZUI/I0xQOISAu2JQLm8Nsv5yYsBhvpksECyDoQl+nqJBhiaMYlHCLRXAnf+rE7yn5k80BD/DBLI3tX+MXMmeKw1JEMShxCwBAJfHi1cP29D1tvN+dqsQPw9xO6Zh0ILm8uoI9xPzpaipFL4SFH4FOAmUSHArRJ2QrojFJWUAUDg9KseWYWKoqZgNCuQnCP9073dbIM6OtEamgfR4gnNFtPbqRrX3joDJ3t1s3FJhPZNIK9IldF12qXuJgukn6+o26WvwmTtu5it493te/YIWBdhUGYigQbK7UdN30QyyAqJ9FcQ6P98sk/Kneq7+mw12YNc3B3624AQ8Zi/wlFz29if0AUv7e9rsBvxUecwyMekvSeDbZCIbU8gKVVxYtDLV8eaJJCaM0M1Aj7V7DCs7YvR9hae29cP3yR61xtiNACtesgwBVA8gC/EDwuTMLm3VUzN2h6+GS3QNMMI/3aBZ7RAQnxF3a7vD5NZhzwAv7cjICux13Gi5PmAplZv1Q2IGov4PluaHGYdu+GOj0/7NsjD2b4GLw3JxdiQFv1E6BG/GABP5y6DmhHo7vEoDYaIbmGJyy8Q86oNboaTcldAw/Cwxf1r9LDNMzidJUZkGKDXC8k+qXqGWXp7h7VzukS+M++xjy2x0Kb4bLt4AtR0/YOEKs8FwDa7xgOzJgqRzsexw2O/3jiD3h+BpGxpo/fZ4Rk7TGutcI+WwD3zM73Z5QQsgrfgfrPm5BoRpBl7uHi3/JfBT9jkIk+z+VlChHV7sxet/zI3tjFf9Qrkh00hhycPd55qCQVsqY8ahoIgcmKDbKjyHL3ZUj27QzN1Cjrx5SgKfFVvPOmy8ZCrBBDyGawcewtphWIcSumsi1+1/ShsBZqWus+lP6HshXE5b3LHL0rPwpWvwL7yESiltW8czHRMwHdezT/vEqv9MFgWw6VRdX8RQqrjL2v/dOH+4SlRqdONEkjC7tDkgSFiq/ilbpHcFp5vPjBPYzSgKvQMLQQCMKuWABQFD0E58gNeb7SBs32P4PVJXB80sFsZElZqe4vAdRHIuqcdyim2HYO9DQ1WoIUVtrAV0nCxV4NmKK7z4lEMawa0Rvsc4/Ma9mgPXl9VNBubS7UiVwTNgz1PBZnaDX5Z27hrE8WX8WOXLdxxhcYOCo0I7vwKCCgaNLQ9Jx8avF8yGdHFs8ADg9rg51tFvO09k8RURcrgl6+GGSWQ+M9D0wb1FDe5RtzeC26of7/cdMeETwbVR69VgVI+OrSg3Fyhmf8iwNe+9jJNkoiD3tsbNaNU8SFZ9iR3b9W4LGx8KpU7tntjAlS1PK7x18b+jOWHe2DbST9dHs72arBp2X2ZqX0LMH9YNiZ+qvUt4x+nEOCm5I4PpnTGzD39ueOTb1zASpsluFTty82J6ODnuOu7yiKwsGAud7yn82484XANoXc24j7toLM3Q3IRB+Xa/Gu6v4DxOasQV9kTbvwKFAa+ZihCi4538YYifcgrV4ONEsj5nb2Th/aSWEUPsvRgT2w/VT+ZppgqUL4eHC9GIAS6eIEJCgBsbRswvO67Su8kNiVHiv6bRnDxQzwVkNqpcTXPEZU1WnHNG5YNkVCDT874cOdOdmq4imuQVVzfeD+bfQ0vh2frhn9zh+Zgz3NXUKXmQ7z0SbATzDHB93B8UTwcM/ZwvQIFBsPsMlFEOyKzxpPLm712P2gBnDN2gQHFiSjIJh/ZaldUMTZcHAGl4QTilrkTJbQYTzhcxbGuH1h0wzfU+QvX5SnhC68Z14MciAk+PCPCxSrmIGEbR+JyrqOOJzVrHBh3lyb59hPJcMlnjd44H570w4rDPRq9H9a1HOdXnOd6Eza8MvwuWDGw4fDlzpixW9sz3Fh7BiGecvTfNBIpOY7ccIwdlvVaPwo3C8Sw4WtQuf0Y1xvx0v7VqC12qHSu2zvYVDIF/1WEcUOn8qD5cOBpl7Dt0vdBxQjgLShFTsBiCNK+ggYUtrp/jaUuxwxtYxYd7+Dp0iMz16RNM6oHWTrLK3JzpM/HPCvYBWGfxnVPdg7SqzMAQf1y6cPgRtqn4dRj73FPZn1hfOxgHE91426vm5gBBxsancQ1GN+jCJ6OKpzJdMXoj7SvJtTNRdjjB3f0Kz86yvUycemdMGaH9hWczdNSEXU4hDtOif4dfbpUQKmxhSRjL3etl20OXpCe4+YTA0S3EW6fwYnCLv1LqBhhg7kIG98j81MU046YKknCt16xEKXv4/JJ9nkLfUV6N5gtWhAPOq9hgKhY2aJt3/9p3CoWuw+S/EVfma1Q7x5Kh4DENnH+65MalmXRMw3On3U8z61Y9RPdxVOSS5DyKpstu8eqcShW2MBGoEH19qOPxH9w3lPX0NlIQzeHI0HmrJ2cx/7EpWOHUoJI7YS/LrBDtN3PXtUKpdoH/WXvcscnH9uA0fY3H7Fnk/5P1DJ8+AsLkem/nLt/TdUVfe5oX7L73PMLjLa/gaDbW7lzedA8XS/TbGEtOIJKrUHY3MvG74OwZS78aaDGzUnYofsQebUA0uXj66tYwAde/bvuXMxToSJontFNgF02ZlenAt2VSF936pH0bI/F9lx1wUtajXsKG25yzgZ2sl6y+Vfd/eFbw/HHbWfunJ2vlG6pv7e1dCKiimZz94oDF3JLvA+HsTnROKnsyV1mh1cOlIqbp9SFm34rkVAVgDn5CxpM9I0uuIUlKC5TMx6TEo3fSWfLeWRj8G+Tw13G8DpwJ5J41wmDPxiuq1bKzQnMM/WCCRPJkNTEXKOx9sBuOLIbj2xYMDwbO2drn/QPh93nH8PCb0J1PQO7eXgjX8KtYj3e/R5+WxyvS7Lk3z2x4/+78rkbToAVVF2YmBOFY8o+3Ckd/HyjQz81w0e3rB0oqNVuXLL7G6tcfsS7JU9z51Xd52B+/nx8XREOJ34lSgMXWFhTN95ddnj147nSE1Oj00z7LRY7zPpjZx+Z1KHjfs2H3QOJORqoo5vkMhgXu47WnS93OYrN7t8YTZ8dFrGhuZ/qsPHKq4XcHEXI12jFwjRMl14oRkjMKC6/96akIfqJW4/4w65OcfaamBex9ys1tqgFD468Ki7+w+m0q1z651ZGg2jHCcqVNIYtvKJ3eKXl2Uw4/UnP9PDejkF8a5itAxifsxLHlaE6Kr92fR9jHbQrTOYI7DCNHYpVq3nwda1EVkycOdzocDZpDYPzVysyRkXeMP19EJYK+0bh77uCCzu7atfLO3o4UDEEqTVeXDHZlaDVnX7gVoHMFQoqbPH5uW7ck2zFmCxuqZeElhPIL6nByAVpLX+jkHXl7bneMUtndVnbkYdaLUdOcrAUAuzQatv3uetjvshr+TvpdYU+sin44uP9pQPFdh13PmIpFUz8NJ2AsopG3KWKpKfeTG29r5rUuXNiR69bA7o7+Dt24Em76ehJyvZOoEJJ41K6Muvxxddb/7tYdYU/sD44fkQfyWA3JyE68vJve69s4p/hBDQaoLhMjbPX5Akz30oz6qugza5iNebGstmdo+dN9NzQ1cMGDiJ+s0uZhheFxCQEWo8Au4SurKaRU1iDvT8XrP7w2/y2/zZvnftOTnDatTworre/Qz8PFyHYuQmfr/2lKAmEgLkIsOuNNM1AUUWjsFSNa1nKlAVbMyLKyv7Cr7s/WHhPT7hFP+MbO7iHZLpUzOdL7Pmws+VBwIqF/cYBkYy52opV2GXAcL9Vq6UZVKk0kFfSKFfQdMJN+aGN392JLChAi17+b9UHvrcErgP7uowK9XcY7e4iDALFkH+YsopmauZCMpSiuEydeSVTGZd4ufR0nhzt5x+mzIyGmCcE2pRAq/YgbeopyZwQMAMBIhAzQCcmLYcAEYjl1BXx1AwEiEDMAJ2YtBwCRCCWU1fEUzMQIAIxA3Ri0nIIEIFYTl0RT81AgAjEDNCJScshQARiOXVFPDUDASIQM0AnJi2HABGI5dQV8dQMBIhAzACdmLQcAkQgllNXxFMzECACMQN0YtJyCBCBWE5dEU/NQIAIxAzQiUnLIUAEYjl1RTw1AwEiEDNAJyYth8D/APRdIobyv7EYAAAAAElFTkSuQmCC'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

TINYMCE_DEFAULT_CONFIG = {
    "menubar": "file edit view insert format tools table help",
    "plugins": "advlist autolink lists file link image charmap print preview anchor searchreplace visualblocks code fullscreen insertdatetime media table paste code help wordcount spellchecker insertfile",
    "toolbar": "undo redo | bold italic underline strikethrough | fontselect fontsizeselect formatselect | alignleft "
    "aligncenter alignright alignjustify | outdent indent |  numlist bullist checklist | forecolor "
    "backcolor casechange permanentpen formatpainter removeformat | pagebreak | charmap emoticons | "
    "fullscreen  preview save print | insertfile image media pageembed template link anchor codesample | "
    "a11ycheck ltr rtl | showcomments addcomment code",
    "custom_undo_redo_levels": 10,
    "language": "en",  # To force a specific language instead of the Django current language.
    "file_picker_types":'image',
    'image_title': True,
    'automatic_uploads': True,
    'file_picker_callback': """function (cb, value, meta) {
        var input = document.createElement("input");
        input.setAttribute("type", "file");
        if (meta.filetype == "image") {
            input.setAttribute("accept", "image/*");}
        if (meta.filetype == "media") {
        input.setAttribute("accept", "video/*");}

        input.onchange = function () {     
            var file = this.files[0];
            var reader = new FileReader();
            reader.onload = function () {
                var id = "blobid" + (new Date()).getTime();
                var blobCache =  tinymce.activeEditor.editorUpload.blobCache;
                var base64 = reader.result.split(",")[1];
                var blobInfo = blobCache.create(id, file, base64);
                blobCache.add(blobInfo);
               cb(blobInfo.blobUri(), { title: file.name });
             };
             reader.readAsDataURL(file);
         };
         input.click();
      }"""
}
TINYMCE_SPELLCHECKER = True
TINYMCE_FILEBROWSER = True
# TINYMCE_COMPRESSOR = True




# # استخدام قاعدة البيانات كـ broker و backend
# CELERY_BROKER_URL = 'db+sqlite:///celery_broker.sqlite3'  # للتجربة
# CELERY_RESULT_BACKEND = 'django-db'  # يخزن نتائج المهام في DB
# CELERY_CACHE_BACKEND = 'django-cache'  # اختياري
# CELERY_TIMEZONE = 'UTC'
# CELERY_BROKER_URL = 'memory://'
# CELERY_RESULT_BACKEND = 'cache+memory://'
# CELERY_TIMEZONE = 'UTC'

CELERY_BROKER_URL = 'redis://localhost:6379/0'
CELERY_RESULT_BACKEND = 'redis://localhost:6379/0'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'Asia/Baghdad'  # غيّر بحسب منطقتك




LOGIN_URL = '/dashboard/accounts/Login'