# Generated by Django 4.2.23 on 2025-08-22 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_wallet_private_key_deposit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wallet',
            old_name='wallet_address',
            new_name='address',
        ),
        migrations.AlterField(
            model_name='wallet',
            name='private_key',
            field=models.TextField(verbose_name=1),
        ),
    ]
