# Generated by Django 4.2.23 on 2025-08-22 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_rename_wallet_address_wallet_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='txid',
            field=models.CharField(default=222, max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='wallet',
            name='private_key',
            field=models.TextField(),
        ),
    ]
