# Generated by Django 4.2.23 on 2025-08-22 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_deposit_txid_alter_wallet_private_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='img_base64',
            field=models.TextField(null=True),
        ),
    ]
