# Generated by Django 4.2.23 on 2025-08-24 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_transaction_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='img_base64',
            field=models.TextField(blank=True, null=True),
        ),
    ]
