# Generated by Django 4.2.23 on 2025-08-25 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_wallet_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='total_balance',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=20),
        ),
    ]
